#!/bin/bash
echo Press ENTER to install Installing Pomodoro Timer \
&& read && echo "--== [ You may be asked for $USER 's password to install--not root! }==-" \
&& pamac build gnome-shell-pomodoro --no-confirm \
&& cat $SPINE_DIR/reticulation/dconf-pomodoro.ini | dconf load /org/gnome/pomodoro/ \
&& cat $SPINE_DIR/reticulation/dconf-gnome-favorites.ini | dconf load /org/gnome/shell/

#&& pamac build i3ipc-python-git --no-confirm \
#&& pamac build i3-gnome-pomodoro-git --no-confirm \
