#!/bin/bash
xdg_session_get="$(echo $XDG_SESSION_DESKTOP | tr '[:upper:]' '[:lower:]')"
xreader_or_evince() {
	if hash xreader 2>/dev/null ; then
		xreader -f "${MANU_DIR}/${DOS_DIR}-outline.pdf"
	else
		evince -f "${MANU_DIR}/${DOS_DIR}-outline.pdf"

	fi
}

i3_check() {
	if [ $xdg_session_get = "i3" ] ; then
		i3-msg workspace 2|zathura --mode fullscreen "${MANU_DIR}/${DOS_DIR}-outline.pdf"
	else
		echo "i3 not loaded ... moving on"
	fi
}

pdfopen() {
	if hash zathura 2>/dev/null ; then
		zathura --mode fullscreen "${MANU_DIR}/${DOS_DIR}-outline.pdf"
	else
		xreader_or_evince
	fi
}

tde_check() {
	if pgrep kicker &>/dev/null ; then
		kstart --desktop 2 zathura --mode fullscreen "${MANU_DIR}/${DOS_DIR}-outline.pdf"
	else
		echo "Trinity Desktop not loaded... trying next desktop environment."
	fi
}

plasma_check() {
        if pgrep plasmashell &>/dev/null ; then
                zathura --mode fullscreen "${MANU_DIR}/${DOS_DIR}-outline.pdf"
        else
                echo "Plasma Desktop not loaded... trying next desktop environment."
        fi
}

gnome_check() {
        if [ $xdg_session_get = "gnome" ] ; then
                zathura --mode fullscreen "${MANU_DIR}/${DOS_DIR}-outline.pdf"
        else
            	echo "Gnome 3 Desktop not loaded... trying next desktop environment."
        fi
}

gnome_check
i3_check
plasma_check
tde_check
