#!/bin/bash
xdg_session_get="$(echo $XDG_SESSION_DESKTOP | tr '[:upper:]' '[:lower:]')"
LOAD_PDF="${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"

xreader_or_evince() {
	if ! hash zathura ;
	then
		xreader -f "$LOAD_PDF" || evince -f "$LOAD_PDF"
	else
		echo ""
	fi
}


i3_master_race_check() {
	if [[ "$xdg_session_get" == "i3" ]] ;
	then
		i3-msg workspace 2|zathura --mode fullscreen \
		"$LOAD_PDF"
	else
		zathura --mode fullscreen "$LOAD_PDF"
	fi
}



i3_master_race_check

xreader_or_evince

#xreader_or_evince
# obscure_wm_check(){
# 	if pgrep kicker &>/dev/null || exit
# 		then
# 			kstart --desktop 2 zathura --mode fullscreen \
# 			"$LOAD_PDF"

