#!/bin/bash
xdg_session_get="$(echo $XDG_SESSION_DESKTOP | tr '[:upper:]' '[:lower:]')"
LOAD_EPUB="$SYNC_ROOT/WIPs/$MANUSCRIPT/epub/$TITLE-$DATE.epub"

calibre_loaded_check() {
        if ! pgrep calibre ;
        then
		xdg-open $SYNC_ROOT/WIPs/$MANUSCRIPT/epub
        else
		echo "fix me ... nothing opened. Chek $SYNC_ROOT/WIPs/$MANUSCRIPTS/epub for output. Or, ya know, just get back to fucking writing."
fi
}

gnome_master_race_check() {
        if [[ "$xdg_session_get" == "gnome" ]] ;
        then
		calibre \
		"$LOAD_EPUB"
        fi
}


gnome_master_race_check || calibre_loaded_check

