#!/bin/bash
xreader_or_evince() {
	if hash xreader 2>/dev/null ; then
		xreader -f "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
	else
		evince -f "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
	fi
}

i3_check() {
	if [ $DESKTOP_SESSION = "i3" ] ; then
		i3-msg workspace 2|zathura --mode fullscreen "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
	else
		echo "i3 not loaded ... moving on"
	fi
}

pdfopen() {
	if hash zathura 2>/dev/null ; then
		zathura --mode fullscreen "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
	else
		xreader_or_evince
	fi
}

tde_check() {
	if pgrep kicker &>/dev/null ; then
		kstart --desktop 2 zathura --mode fullscreen "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
	else
		echo "Trinity Desktop not loaded... trying next desktop environment."
	fi
}

plasma_check() {
        if pgrep plasmashell &>/dev/null ; then
                zathura --mode fullscreen "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
        else
                echo "Plasma Desktop not loaded... trying next desktop environment."
        fi
}

gnome_check() {
        if [ $DESKTOP_SESSION = "gnome" ] ; then
                zathura --mode fullscreen "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/pdfs/${TITLE}-${DATE}.pdf"
        else
            	echo "Gnome 3 Desktop not loaded... trying next desktop environment."
        fi
}

gnome_check
i3_check
#plasma_check
#tde_check
