#!/bin/bash
i3status_check() {
	if pgrep i3status &>/dev/null ; then
		i3-msg workspace 3|calibre "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/epub/${TITLE}-${DATE}.epub"
	else
		echo "i3 not loaded ... moving on"
	fi
}

tde_check() {
	if pgrep kicker &>/dev/null ; then
		kstart --desktop 3 calibre "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/epub/${TITLE}-${DATE}.epub"
	else
		echo "Trinity Desktop not loaded... trying next desktop environment. What are you running. Please tell ja.norseman@pm.me"
	fi
}

plasma_check() {
        if pgrep plasmashell &>/dev/null ; then
 		calibre "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/epub/${TITLE}-${DATE}.epub"
        else
                echo "Plasma Desktop not loaded... trying next desktop environment."
        fi
}

gnome_check() {
        if pgrep -l "gsd-keyboard" &>/dev/null ; then
 		calibre "${SYNC_ROOT}/WIPs/${MANUSCRIPT}/epub/${TITLE}-${DATE}.epub"
        else
            	echo "Gnome 3 Desktop not loaded... trying next desktop environment."
        fi
}

gnome_check
i3status_check
#plasma_check
#tde_check
