#!/bin/bash
source $SPINE_DIR/reticulation/gen_wordsmith_profile \
&& cat $ASSET_DIR/dconf-caps_as_control.ini \
| dconf load /org/gnome/desktop/input-sources/ \
&& cat $ASSET_DIR/dconf-wordstar-background.ini \
| dconf load /org/gnome/desktop/background/ \
&& rm /home/$USER/.config/autostart/initial-config.desktop
