#!/bin/bash
# Note: script fix_up ... copying of asset from wordsmith to gem folder 
# probably won't work on distros other than Manjaro 19.02 with current implementation
source $SPINE_DIR/reticulation/gen_wordsmith_profile \
gem install wordsmith bundler \
&& cp $ASSET_DIR/generate.rb \
$HOME/.gem/ruby/2.7.0/gems/wordsmith-0.0.6/lib/wordsmith/ \
&& cat $SPINE_DIR/reticulation/dconf-gnome-favorites.ini | dconf load /org/gnome/shell/ \
&& rm $HOME/.config/autostart/initial-wordstar-setup.desktop
