#!/bin/bash
# Note: script fix_up ... copying of asset from wordsmith to gem folder
# probably won't work on distros other than Manjaro 19.02 with current implementation
# especially if you're using rvm
# fix_up ... move *.ini files to $ASSET_DIR and update all code
RVM_DIR="$HOME/.rvm/gems/default"
source "$SPINE_DIR/reticulation/gen_wordsmith_profile"; \

rvm_exist(){
if [ -L "$RVM_DIR" ]; then
	echo "RVM Exists...Installing Wordsmith for RVM."
	rm -rf wordsmith; \
	git clone https://github.com/perezsan/wordsmith.git \
	&& cd wordsmith \
	&& source ~/.rvm/scripts/rvm \
	&& rvm default \
	&& bundle install \
	&& gem install bundler \
	&& rake build \
	&& gem install pkg/wordsmith-0.0.6.gem
else
	echo "Installing wordsmith to ~/.gem...."
	rm -rf wordsmith; \
	git clone https://github.com/perezsan/wordsmith.git \
	&& cd wordsmith \
	&& bundle install --path ~/.local/share/gem \
	&& gem install --user bundler \	
	&& rake build \
	&& gem install --user pkg/wordsmith-0.0.6.gem
fi
}

rvm_exist \
&& cat $ASSET_DIR/dconf-gnome-favorites.ini | dconf load /org/gnome/shell/

# used for dedicated Manjaro Gnome 3 distro ...
#plus other users may not want pcmanfm as default file manager
#&& xdg-mime default pcmanfm.desktop inode/directory \

# only needed for dedicated Manjaro Gnome 3 distro
#&& rm $HOME/.config/autostart/initial-wordstar-setup.desktop
