#!/bin/bash
# Blocks internet traffic ... use in conjuction with pomodoro. This solution may not wrok
# on blocking all internet traffic, say if you had eth0 up and wan0 up simulateously

source $SPINE_DIR/reticulation/test-connectivity \
&& echo "echo $ACTIVE_INTERFACE" > $HOME/.active.interface \
&& echo "Internet connection is at $ACTIVE_INTERFACE..." \
&& sudo iptables -I OUTPUT -o $ACTIVE_INTERFACE -j DROP \
&& echo "Firewall enabled to block all traffic on $ACTIVE_INTERFACE. Please run firewall-off to regain connectivity on $ACTIVE_INTERFACE"


