#!/bin/bash
subl3_check() {
        if hash subl3 2>/dev/null ; then
		source $SPINE_DIR/reticulation/gen_wordsmith_profile \
		&& subl3 $ASSET_DIR/Cheat\ sheet\ -\ BEGINNERS\ GUIDE.md
        else
		source $SPINE_DIR/reticulation/gen_wordsmith_profile \
            	&& gedit $ASSET_DIR/Cheat\ sheet\ -\ BEGINNERS\ GUIDE.md
        fi
}

subl3_check
