#!/bin/bash
SCRIPTNAME=".tmp.start.outline.pdf"
pomodoro_check () {
if ls $HOME/.active.* 1> /dev/null 2>&1; then
  echo "internet down ... stop pomodoro timer to regain connectivity, or run 'firewall-off'"
else
  echo "We have purposeful connectivity ... proceeding!" \
  && $HOME/$SCRIPTNAME
fi
}

clear_tmp() {
	if ls $HOME/$SCRIPTNAME 1> /dev/null 2>&1; then
                echo "removing dangiling .tmp file ... something didn't finsh executing, perhaps?"
                rm $HOME/$SCRIPTNAME
        else
            	echo "No old tmp files hanging about ..."
        fi
}

clear_tmp

cd $SPINE_DIR
cat $SPINE_DIR/reticulation/gen_wordsmith_profile >> $HOME/$SCRIPTNAME \
&& cat $SPINE_DIR/reticulation/gen_pandoc_pdf >> $HOME/$SCRIPTNAME \
&& cat $SPINE_DIR/reticulation/load_outline_pdf >> $HOME/$SCRIPTNAME \
&& chmod 755 $HOME/$SCRIPTNAME \
&& pomodoro_check; \
clear_tmp

exit 0
