#!/bin/bash
spine_check() {
        if ls /livefs-pkgs.txt 1> /dev/null 2>&1; then
                echo livefs is loaded ... aborting. Install Wordstar Linux to Hard Drive first.
        else
                $SPINE_DIR/spine.py
        fi
}

spine_check
