#!/bin/bash
subl3_check() {
        if hash subl3 2>/dev/null ; then
                subl3 "$ASSET_DIRCheat\ sheet\ -\ BEGINNERS\ GUIDE.md"
        else
            	gedit "$ASSET_DIR/Cheat\ sheet\ -\ BEGINNERS\ GUIDE.md"
        fi
}

subl3_check
