#!/bin/bash
echo "-== [ Change SPINE_DIR ... ]-- " \
&& echo "-== [ Only Use if downloaded from git, or if you know what you're doing!!! ] ==-" \
&& echo "$SPINE_DIR_NEW" | sed 's/ /\\ /g' \
&& echo "$SPINE_DIR_NEW" \
&& echo export SPINE_DIR=$SPINE_DIR_NEW > "$HOME/.profile_spine" \
&& echo export PATH=$PATH:$SPINE_DIR_NEW >> "$HOME/.profile_spine" \
&& echo source "$HOME/.profile_spine" >> "$HOME/.bashrc" \
&& echo source "$HOME/.profile_spine" >> "$HOME/.profile"



exit 0
