#!/bin/bash
# Archive WIPs
DATE=$(date +%F)

source $SPINE_DIR/reticulation/gen_wordsmith_profile
echo "-==[ Archiving WIP Folder ]==-"
tar -czvf \
$ARCHIVE_DIR/$TITLE_DIR$VERSION/$TITLE_DIR$VERSION-WIPs-$DATE.tar.gz \
-C $WIP_DIR ../$TITLE_DIR$VERSION
