#!/bin/bash
source $SPINE_DIR/reticulation/gen_wordsmith_profile
echo "-==[ Archiving Project Folders ]==-"
tar -czv -C $CLOUD_DIR manuscripts/Novels DOS/WS/WIPS \
| gpg2 -c -o $ARCHIVE_DIR/Everything-$DATE.tar.gz.gpg
