#!/bin/bash

TITLE_DIR_NEW=$(echo "$TITLE_DIR_NEW" | sed 's/ /\_/g') \
&& source "$SPINE_DIR/reticulation/gen_wordsmith_profile"; \
mv "$MANU_DIR" "$SYNC_ROOT/$FORMAT/$TITLE_DIR_NEW$VERSION"; \
DOS_DIR=$(echo "$TITLE_DIR_NEW" | tr -d '[:space:]' | tr -d '[=_=]' | tr -d '[=-=]' | cut -c -7 | sed "s/[a-z]/\U&/g"); \
mv $SYNC_ROOT/$FORMAT/$TITLE_DIR_NEW$VERSION/*-outline.md "$SYNC_ROOT/$FORMAT/$TITLE_DIR_NEW$VERSION/$DOS_DIR-outline.md"; \
sed -i.bak "s/DOS_DIR=.*/DOS_DIR=$DOS_DIR/g" $SPINE_DIR/reticulation/gen_wordsmith_profile \
&& TITLE=$(echo "$TITLE_DIR_NEW" | sed 's/\_/ /g') \
&& sed -i.bak 's,TITLE=.*,TITLE=\"'"$TITLE"'\",' "$SPINE_DIR/reticulation/gen_wordsmith_profile" \
&& sed -i.bak 's,TITLE_DIR=.*,TITLE_DIR=\"'"$TITLE_DIR_NEW"'\",' "$SPINE_DIR/reticulation/gen_wordsmith_profile" \
&& $SPINE_DIR/reticulation/close-subl-check \
rm "$HOME/.config/sublime-text-3/Local/Session.sublime_session"; \
cp "$ASSET_DIR/Session.sublime_session" "$HOME/.config/sublime-text-3/Local" \
&& source "$SPINE_DIR/reticulation/gen_wordsmith_profile"; \
sed -i.bak 's,path.*,path\"\: \"'"$MANU_DIR"'\"\}\,\{ \"path\"\:\ \"'"$WIP_DIR"'\",' "$HOME/.config/sublime-text-3/Local/Session.sublime_session" \
&& sed -i.bak 's,expanded".*,'"$MANU_DIR"'\"\,\"'"$WIP_DIR"'\",' "$HOME/.config/sublime-text-3/Local/Session.sublime_session"; \
sed -i.bak 's/title:.*/title:    '"$TITLE"'/g' "$SYNC_ROOT/$FORMAT/$TITLE_DIR_NEW$VERSION/.wordsmith"; \
start-gen-wordsmith-project \
&& $SPINE_DIR/reticulation/reopen-subl-check \


