#!/bin/bash
echo "-== [ Author\'s Name ] ==-" \
&& echo "$AUTHOR" | sed 's/ /\\ /g' \
&& echo "$AUTHOR" \
&& sed -i.bak 's,AUTHOR=.*,AUTHOR=\"'"$AUTHOR"'\",' "$SPINE_DIR/reticulation/gen_wordsmith_profile" \
&& sed -i.bak 's,GITUSERNAME=.*,GITUSERNAME=\"'"$AUTHOR"'\",' "$SPINE_DIR/reticulation/gen_wordsmith_profile" \
&& source $SPINE_DIR/reticulation/gen_wordsmith_profile \
&& echo $MANU_DIR \
&& sed -i.bak 's,author.*,author: '"$AUTHOR"',' "$MANU_DIR/.wordsmith" \



exit 0
