#!/bin/bash
DATE=$(date +%F)

source $SPINE_DIR/reticulation/gen_wordsmith_profile
echo "-==[ Archiving Project Folder ]==-"
tar -czvf $ARCHIVE_DIR/$TITLE_DIR$VERSION/$TITLE_DIR$VERSION-$DATE.tar.gz -C $MANU_DIR ../$TITLE_DIR$VERSION -C $CLOUD_DIR/DOS/WS/WIPS $DOS_DIR
